### ISSUE TITLE
Doesn’t work

### ISSUE THREAD

**Issue by IvanYurchenko** [codetrash/rest-crud#4]
After successful installation and starting of the server, it says "Welcome" but when I go to any URL (e.g. "localhost:3000/user") it shows an error page: "Cannot GET /user". The database was created and seeded using the t_user.sql file.

```
mysql> select * from t_user;
+---------+------------+--------------------+--------------------+
| user_id | name       | email              | password           |
+---------+------------+--------------------+--------------------+
|       1 | Mas Banyar | banyar@yahoo.com   | 23235645yghgf      |
|       2 | Mas Mapmup | mapmup@gmail.com   | dncskdcndscsdcdsc  |
|       4 | Boronong   | borononn@yahoo.com | 032bcsjdncsdjc3223 |
|       5 | Nadya Ek   | nadya@yahoo.com    | bonbon032932       |
+---------+------------+--------------------+--------------------+
4 rows in set (0.00 sec)
```

Are there any additional instructions that are required to make it work despite not being mentioned in the project readme?

**Comment by codetrash** [comment]
others did it successfully....but I'll check it tomorrow morning...

**Comment by codetrash** [comment]
shouldn't it be localhost:3000/api/user ? 

take a look at http://teknosains.com/i/restful-crud-example-with-nodejs-and-mysql

**Comment by IvanYurchenko** [comment]
Yes, thank you, it was my mistake. I didn't notice I should add the "/api" to the route.
